brew cask install alfred
brew cask install docker
brew cask install gimp
brew cask install iterm2
brew cask install slack
brew cask install atom
brew cask install dropbox
brew cask install google-chrome
brew cask install firefox
brew cask install google-japanese-ime
